### ISSUE TITLE
Add/Edit/remove property on node.

### ISSUE THREAD

**Issue by dimio111** [Adobe-Consulting-Services/curly#28]
It would be a nice feature if it was possible to add, change and remove properties from nodes.
This could then be used to perform content jobs on aem instances.

**Comment by badvision** [comment]
Essentially you can do this already -- though there may not be a proper example for this the sling post servlet does allow for this: https://sling.apache.org/documentation/bundles/manipulating-content-the-slingpostservlet-servlets-post.html#setting-property-values
