### ISSUE TITLE
Slow performance after AEM 6.4 upgrade?

### ISSUE THREAD

**Issue by matssonadam** [Adobe-Consulting-Services/curly#31]
First of all -THANKS FOR THIS TOOL IT'S AMAZING.
Second - We struggle with the load times when performing a roll out sequence with Curly. Before we upgraded to AEM 6.4 from 6.3 it was much faster (I believe this is when it happened).
We are using this Action in Curly:
<command>-F cmd=rollout -F path=${node path master|/content/path/to/masterpage} -F msm:targetPath=${node path target|/content/path/to/targetpage} -F type=page -F reset=false -F _charset_=utf-8 ${server}/bin/wcmcommand</command>
    </action>
</actions>
Before it took around 20-40 minutes for the tool to roll out around 500 pages, now it takes 3-4 hours even though we are using concurrency as 2.
Might be our servers as well, not sure. However our IT team does not have any clue how this works so I'm reaching out to you for help. 
Thanks!

**Comment by badvision** [comment]
First of all, you are quite welcome.  As for the performance, it's definitely an aem side issue and related to what is happening on the server when performing those actions.  The best way to troubleshoot from here is to run profiling of the jvm during these actions and look for hot spots, such as slow queries and such.  Also look at the query stats in aem to see if there are any common queues running slowly that need indexes.

**Comment by badvision** [comment]
I think I fixed it recently, I changed how I was authenticating to AEM and now it picks up the J_Session_Id cookie, speeding up operations at least 4x.
